require("marcus.set")
require("marcus.lazy")
require("marcus.remap")
require("marcus.markdown2pdf")
require("marcus.globals")
require("marcus.autocmd")
require("marcus.paste_url")
require("marcus.miki")
require("marcus.quickfix")
require("marcus.dotnet")
-- require("marcus.session-plugin")
